services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile-nginx-dev
    depends_on:
      - express
    ports:
      - "8081:3000"
    environment:
      - EXPRESS_HOST_1=backend-dev-express-1
      - EXPRESS_HOST_2=backend-dev-express-2
      - EXPRESS_PORT=3000
      - NGINX_SERVER_NAME=localhost
      - NGINX_MAX_BODY=100M
  express:
    build:
      context: .
      dockerfile: Dockerfile-dev
    depends_on:
      - database
    environment:
      - NODE_ENV=dev
    volumes:
      - .env.dev:/app/.env.dev
    scale: 2
  database:
    image: mongo:8.2.7-noble
    container_name: devops-database-dev
    ports:
      - 27018:27017
    volumes:
      - devops-database-data:/data/db
volumes:
  devops-database-data:
