services:
  load-balancer:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    depends_on:
      - express
    restart: unless-stopped
    environment:
      - EXPRESS_HOST_1=backend-prod-express-1
      - EXPRESS_HOST_2=backend-prod-express-2
      - EXPRESS_HOST_3=backend-prod-express-3
      - EXPRESS_PORT=3000
      - NGINX_SERVER_NAME=localhost
      - NGINX_MAX_BODY=100M
    networks:
      - proxy-net
  express:
    image: devsororm/devops-backend:${IMAGE_TAG:-latest}
    depends_on:
      - database
    restart: unless-stopped
    env_file:
      - .env.prod
    scale: 3
    networks:
      - proxy-net
  database:
    image: mongo:8.2.7-noble
    container_name: devops-database
    restart: unless-stopped
    volumes:
      - devops-database-data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASS}
    networks:
      - proxy-net
volumes:
  devops-database-data:
networks:
  proxy-net:
    external: true
